### ISSUE TITLE
Cannot use it in various mozilla sites.

### ISSUE THREAD

**Issue by yuliu** [Speedkore/draglinks#2]
Other sites seem OK to use this extension within. But in Mozilla sites, such as Firefox homepage, any amo page, this extension has no effect on dragging any link, as well as selected text to search is not usable.

Firefox 57 64bit, Windows 10
draglinks 1.9

**Comment by Speedkore** [comment]
For security issues Firefox prevents the use of add-ons/webextensions in their own sites.

**Comment by yuliu** [comment]
Well, I see. Other alternatives has this issue, too.

Another.. not quite a problem, perhaps the icon, appearing when dragging occurs, could be replaced by some indicating ones.
